#!/bin/bash

# Local scripts
rsync -aP --delete /usr/local/bin/ localbin/
cp /etc/profile.d/zsh.sh .

# Portage and Layman configurations
mkdir portage
rsync -aP --delete /etc/portage/ portage/portage/
rsync -aP --delete /usr/local/portage/ portage/localoverlay/
cp /var/lib/portage/world* portage/
grep / /var/lib/layman/make.conf | sed 's/[a-z]*\///g' > portage/layman-overlays

# XMonad configurations
rsync -aP --delete ~/.xmonad/ xmonad/
rm xmonad/xmonad{.o,.hi,-x86_64-linux}

# Taffybar
rsync -aP --delete ~/.config/taffybar/ taffybar/

# Udev configurations
rsync -aP --delete /etc/udev/rules.d/ udev-rules/

# Vim configurations
mkdir vim
cp /etc/vim/vimrc.local vim/
cp /etc/vim/gvimrc.local vim/
ls /usr/local/bundle > vim/plugins

# /etc/fstab
cp /etc/fstab .

# Systemd services and configurations
rsync -aP --delete /etc/systemd/ systemd/

# screen and tmux configurations
#cp /etc/screenrc .
cp /etc/tmux.conf .

# Zsh
rsync -aP /etc/zsh/ zsh/

# Mpd
sed 's/".*@/"********@/g' ~/.mpd/mpd.conf > mpd.conf

git status
