#!/bin/bash

function copy() {
	rsync -aRP --delete --keep-dirlinks $1 .
}

copy ~/.config/systemd
copy ~/.config/taffybar
copy /etc/fstab
copy /etc/portage
copy /etc/systemd
copy /etc/tmux.conf
copy /etc/udev/rules.d
copy /etc/vim
copy /etc/X11
copy /etc/zsh
copy ~/.mpd/mpd.conf
copy /usr/local/bin
copy /usr/local/portage
copy /var/lib/portage
copy ~/.xmonad

rm etc/vim/ycm_exta_conf.pyc
rm home/cuki/.xmonad/xmonad.errors
rm home/cuki/.xmonad/xmonad-x86_64-linux
find home/cuki/.xmonad/ -iname \*.o | xargs rm
find home/cuki/.xmonad/ -iname \*.hi | xargs rm

git status
