#!/bin/bash
BF=/sys/class/backlight/intel_backlight/brightness
CB=`cat $BF`
if [[ 0 = $# ]]
then
	echo $CB
fi
if [[ 1 != $# ]]
then
	exit
fi
if [[ up = $1 ]]
then
	echo $((CB+100)) | tee $BF
elif [[ dn = $1 ]]
then
	echo $((CB-100)) | tee $BF
else
	echo $1 | tee $BF
fi
